### PR TITLE
Ensure the `Signout`-button has the destructive red text colour

### LINKED ISSUE #515: Sign Out button lacks destructive coloring
@rnystrom Super minor but storyboard says it should be red 🤔 Weird one

(Latest TF build)

### PR DESCRIPTION
**Pull request by weyert**
Fixes #515

### CODE REVIEW

**Comment by weyert** [comment]
@rnystrom Probably, only then we need to go through all the code where `StyledTableCell` is used and ensure the colour properly set.

**Comment by rnystrom** [comment]
Took care of this myself, all good to just clean up the base class

**Comment by BasThomas** [comment]
Wasn’t it also centered? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
A while ago ya, not anymore 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
