### PR TITLE
Design polish

### LINKED ISSUE #1271: Outlook style tab bar colors
I kind of love these. Thoughts?

GitHawk Upload by rnystrom

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513090523)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by rnystrom**
Fixes #1271, #1263, #793, #1262

### CODE REVIEW

**Comment by rnystrom** [comment]
Not gonna lie, I'm in love

img_0546
img_0547
img_0548
img_0549

**Comment by Sherlouk** [comment]
I'm sure they'll grow on me but not completely sold 🤔 

Mainly the last two icons, might be the thick & near stroke I dunno

**Comment by BasThomas** [comment]
Not too keen on this :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas give it time 😎

Ya boosting titles might be in order

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Also what about the “milestones” button being “milestone” whereas all other buttons are plural? Even the milestone edit view says “Milestones”!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
@BasThomas is it because a pull request can only have one milestone, but the edit page is displaying multiple milestones for you to pick from?

Labels/etc can have multiple of them on a pull request

**Comment by BasThomas** [comment]
🤔 yeah you're right, nevermind me

**Pull request merged**
