### PR TITLE
Redesign issue comments with a card

### LINKED ISSUE #1315: Issue comment redesign
Had a productive morning getting feedback from @orta. One big discussion we had was GitHawk's use of whitespace to achieve a visual information hierarchy (or lack there of).

After some brainstorming, I decided to play around w/ a "card" design for comments. I've been pretty averse to the idea b/c I dread _double padding_ and wasting precious space for text.

However, after looking at other apps and playing w/ some mockups, I think this makes reading GitHawk threads so much more readable.

I still want to play with the header spacing a bit and organize/prioritize the title + metadata correctly, but wanted to post this mockup and get some early feedback.

Some stuff I'm playing w/

- 10pt padding instead of 15 (2x 10pt on the cards)
- 15pt between card metadata and content (header, reactions)
- New "more" indicator (get this feedback a lot)
  - Might work on extending IGListKit w/ decorator support to make this more manageable

cc @BasThomas @Sherlouk 

redesign-mocks

### PR DESCRIPTION
**Pull request by rnystrom**
I dig this

simulator screen shot - iphone x - 2017-12-30 at 18 32 28

Fixes #1315

### CODE REVIEW

**Comment by rnystrom** [comment]
Couple notes:

- I spent some time getting pixel-snapping perfection here. Some interesting learnings, maybe a quick blog post
- Title/metadata padding needs some love. Might expand it to the same padding as everything else? Or should it align to the content of the card?

**Comment by Sherlouk** [comment]
Looks so nice! The inconsistant padding hurts my head a little, but I know that's getting changed so yeah!

How does it look with the header area with a background (how "my" comments are blue, etc)

I wonder if it's worth a small horizontal line above the reaction zone to just add a minor break there? Not sure if it adds much but in my head I quite like it

**Comment by rnystrom** [comment]
Thanks for pointing out the "your" background-blue @Sherlouk! I missed that. Might require a little reconfiguring since its an actual view atm... The whole clipping background and pixel-snapping is tricky.

**Comment by BasThomas** [comment]
What about insetting the events too?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by orta** [comment]
> What about insetting the events too?

Good eye @BasThomas - this was the first thing I thought of when I saw the image

screen shot 2017-12-31 at 8 36 13 am

**Comment by rnystrom** [comment]
Merging now, can polish and fix other issues in new PRs as they come up

**Pull request merged**
