### PR TITLE
Sort milestones by due date and title

### LINKED ISSUE #1341: Sort milestones by due date and title
Should be from low > high or opposite?

GitHawk Upload by BasThomas

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1514903367)
Device: iPad7,3 (iOS 11.2.1)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by vanyaland**
Closes #1341 

## Example screenshot:

simulator screen shot - iphone x - 2018-01-08 at 23 20 44

#### @rnystrom maybe sort like GitHub - by title?

screen shot 2018-01-08 at 23 30 01

### CODE REVIEW

**Comment by rnystrom** [comment]
THANK YOU! 🙏🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Nice! Might be a bit easier to read using a [`switch`](https://basthomas.github.io/switches-and-cases), but 👍

**Comment by vanyaland** [comment]
@rnystrom @BasThomas, update to `switch` statement?

```
milestones.sort { lhs, rhs in
                    switch (lhs.dueOn, rhs.dueOn) {
                    case (let lhsDue?, let rhsDue?):
                        return lhsDue.compare(rhsDue) == .orderedAscending
                    case (_?, nil):
                        return true
                    case (nil, _?):
                        return false
                    default:
                        return lhs.title < rhs.title
                    }
                }
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Oh huh it seems like BuddyBuild doesn't get triggered for forks 🤔

**Pull request merged**
