### PR TITLE
Log device environment info

### PR DESCRIPTION
**Pull request by rnystrom**
I'd like to get a better understanding of user demographics to prioritize other languages, accessibility, and RTL. Doesn't mean if there are very few users we give up. Also justification for working on stuff, knowing that we're helping ppl.

However I could understand push back against logging ppl's information. If people strongly disagree, I wont merge this.

### CODE REVIEW

**Comment by BasThomas** [comment]
What about a toggle in Settings to turn it off? Would still track it until the user would see that though.

Not opposed though - would love to see these numbers!

**Comment by rnystrom** [comment]
@BasThomas wow what a great idea. I actually think having a toggle to disable ALL logging would be a nice gesture.

**Comment by Sherlouk** [comment]
Fwiw crashlytics has a delegate to stop tracking etc so would explore that!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Oh yeah, that's what I meant. :)

**Pull request merged**
