### PR TITLE
Search for Inbox

### PR DESCRIPTION
**Pull request by weyert**
Search for Inbox,  ticket #485

### CODE REVIEW

**Comment by Sherlouk** [comment]
Yaaaas! Love it!

Wonder how difficult it'd be to drop this into issues/prs in the repo view? (My biggest annoyance at the moment 😅)

**Comment by weyert** [comment]
Hmm, let me look into that! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
@Sherlouk Would you want to separate search for Issues and Pull Requests or do you want to keep the same query? E.g. you search by XYZ and switch to pull requests. Do you want it to apply this same search?

**Comment by Sherlouk** [comment]
Probably search XYZ and switch between issues/prs.

I'm probably super pushing this past the scope of the issue, feel free to isolate it for now and do it as a follow-up but maybe we could also add support for `if:open` `if:closed` like GitHub search? Obviously we wouldn't have a button for it or anything (yet) but it would filter out closed/open respectively?

https://github.com/rnystrom/GitHawk/issues?utf8=%E2%9C%93&q=is%3Aclosed%20GIF

Just firing ideas out!

**Comment by rnystrom** [comment]
Very well done!

**Pull request merged**
