### PR TITLE
Add dependency to Apollo-codegen

### PR DESCRIPTION
**Pull request by Palleas**
Addresses #282.

I figured the best way to do this was to use `yarn` to pin a specific version, let me know if you think it's overkill. 🤔

### CODE REVIEW

**Comment by BasThomas** [comment]
Holy cow, that `yarn.lock` 😱

**Comment by Sherlouk** [comment]
Obviously this comes down to personal preference, but I feel `npm` has been round for a lot longer n more commonly used. Not sure if it's easier just to get people to do `npm install -g apollo-codegen@0.10`.

**Comment by Palleas** [comment]
That make sense, I can switch to npm! That said, I’d recommend using a package.json (especially because people will need npm anyway), that way there is no doc to update when you manage to upgrade Apollo. Let me know what you think! :)

(Contributing to this app using this app is **awesome**)

**Comment by Sherlouk** [comment]
I'm definitely all up for a package.json, at least the steps will be down to just `npm install` and will work for future dependencies (if we get any) and as you say saves us when we update versions!

Can also tie this to #387 to make buddybuild play nicely?

**Comment by Palleas** [comment]
@Sherlouk Done!

**Comment by rnystrom** [comment]
Awesome!!

**Pull request merged**
