### PR TITLE
Add done return key type that dismisses keyboard for notifications/issues/pr search

### PR DESCRIPTION
**Pull request by joerocca**
Gives the return key a purpose and also feels more natural(at least for me) than scrolling to dismiss.

### CODE REVIEW

**Comment by BasThomas** [comment]
Why not `.search`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
I didn’t use .search because search happens in real time. I figured .done makes more sense because you are done searching when you press it.

**Comment by BasThomas** [comment]
Ref #596

**Comment by joerocca** [comment]
Done!

**Pull request merged**
