### PR TITLE
Allow relative images to display in README files

### PR DESCRIPTION
**Pull request by Sherlouk**
Relates to #314 

So this does fix the issue in the GitHawk README, but we're still going to have issues with links going to relative destinations such as to a guide MD file or similar.

Thinking we need to check the file extension, see what the type is?

@rnystrom Advice?

### CODE REVIEW

**Comment by rnystrom** [comment]
Good point. Lets tackle that next.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ah dang, this doesn't work now that I removed issue shorthand from readme's (b/c the `owner` and `repo` is `nil` in that case). Might need to change that into an `options` mask.

**Comment by Sherlouk** [comment]
Ahh bummer! Revert the change and I'll try and approach the issue again!

**Comment by rnystrom** [comment]
@Sherlouk np! This was the right way to do it, just stepped on your toes lol. I'm fixing it up by adding the options mask to MD parsing, that way we can always deliver `owner`+`repo` but add options like issue shorthand, base url, etc and have different parsing behavior on different surfaces.

**Comment by rnystrom** [comment]
Hmm, even after fixing it, I can't get the relative image to show up in the GitHawk readme. I'll push my changes @Sherlouk mind taking a look?

**Comment by Sherlouk** [comment]
Taken a quick look but may need to leave it until morning - The base URL is definitely getting through correctly when the request is being made so bit confused actually

Was definitely working with the original implementation on the GitHawk readme

**Comment by rnystrom** [comment]
Ya the base URL is being used for sure. Maybe it's a simulator issue, trying on device.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Admitting defeat for tonight because I need sleep, will take look tomorrow

Maybe a different approach would be to use a regex detecting relative URLs, iterate through them and prefix them manually before we even render the UIWebView? That way we can switch it out depending on the URL extension (MD different than PNG etc)

**Pull request merged**
