### PR TITLE
Fixes User name on image upload

### LINKED ISSUE #765: Image upload alt text hardcoded to me
https://github.com/rnystrom/GitHawk/blob/012a5b32169982eb1fb939fccf87f9d255360185/Classes/Views/TextActionsController.swift#L63-L65

😂 Oops...

https://github.com/rnystrom/GitHawk/issues/759#issuecomment-339803210

Gets compile issue, hard codes it, doesn't go back and fix it. Tell me I'm not alone? Please? 😞

### PR DESCRIPTION
**Pull request by rizwankce**
Closes #765 

Using real username instead of `Sherlouk` 😆

### CODE REVIEW

**Comment by rnystrom** [comment]
lol

**Comment by Sherlouk** [comment]
😞 Sorry

**Comment by rizwankce** [comment]
Nvm. Every one does!! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Lol if I had a nickel....

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
