### PR TITLE
Fixes referenced issue view controller being pushed without nav bar

### LINKED ISSUE #388: Navigation bar missing in detail view on iPad
e68b5f05-2538-4940-af4d-ae5c54e63a8f

### PR DESCRIPTION
**Pull request by rizwankce**
Fixes #388 

Am I missing something here?

### CODE REVIEW

**Comment by rnystrom** [comment]
Ahhhh you’re right. Nice one.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Admittedly I haven't tried this solution, but shouldn't we be using `pushViewController` from the view controller's navigation controller?

**Comment by rizwankce** [comment]
@Sherlouk tried this solution on both iPad and iPhone and it works fine. I just figured out this from that `show()` actually overrides and handle the presentation. 

From [Documentation](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621377-show)
>The UISplitViewController and UINavigationController classes override this method and handle the presentation according to their design. For example, a navigation controller overrides this method and uses it to push vc onto its navigation stack.

**Comment by Sherlouk** [comment]
Well today I learn, that's pretty helpful actually 🤔 

LGTM

**Comment by rizwankce** [comment]
Even I didn't know this before. After reading your comment was wondering how it was working when I tested. Then checked the documentation to understand the behaviour 👍

**Pull request merged**
