### PR TITLE
Parse issue shorthand within MMMarkdown

### PR DESCRIPTION
**Pull request by rnystrom**
Depends on #1269

### CODE REVIEW

**Comment by Sherlouk** [comment]
Out of interest does the new issue shorthand stuff fix the bug where if it's wrapped in brackets it doesn't detect it? Would be ace to fix that!

**Comment by rnystrom** [comment]
@Sherlouk can you give me an example? You mean like [rnystrom/githawk#1]?

**Comment by Sherlouk** [comment]
(#1)

^ Isn't (currently) detected in GitHawk

**Comment by Sherlouk** [comment]
Also give #146 an open with this fix and make sure it detects the ones in the root comment! Nice quick test!

**Comment by rnystrom** [comment]
Working pretty great now!

simulator screen shot - iphone x - 2017-12-16 at 21 53 04

simulator screen shot - iphone x - 2017-12-16 at 21 53 07

**Comment by Sherlouk** [comment]
Massive improvement!

**Pull request merged**
