### PR TITLE
Open PR comments in another VC

### PR DESCRIPTION
**Pull request by rnystrom**
Using @Sherlouk's idea from #337. Some drawbacks:

- Reactions are totally broken
  - No list of users so detail view isn't visible
  - Don't have GQL id so mutations fail
  - No indication if the viewer has reacted
- Determining author is kind of gross, have to compare usernames
- No editing information
- Can't know if viewer can update

Things unfinished:

- Putting the reviews + comments in proper chronological order w/ the rest of the timeline
- Head/neck/tail position of comments (for borders)

Overall, the code is pretty gross but it _does work_!

simulator screen shot - iphone x - 2017-11-01 at 21 55 11

### CODE REVIEW

**Comment by rnystrom** [comment]
Maybe we just strip reactions for the time being?

**Comment by Sherlouk** [comment]
A quick idea à la Slack - what if you could tap on a comment to see the full thread with edit/reactions etc? (Use the comment ID to load full GQL response?)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I like the tapping on comments idea, but still leaves us stuck w/ reactions being broken. I actually don't mind the inline comments, tho it would be nice to collapse ones that are outdated. Maybe we should explore that... 

For each PR review we could add a button that says "view comments" or something. We can query the total number of **root** comments on each review, so the UI could say "View comments (2)", or we just drop comments entirely and put a "View comments" button, omitting if 0.

@Sherlouk @BasThomas @heshamsalman thoughts?

**Comment by rnystrom** [comment]
Ok I'm actually really digging this idea. It cleans up `IssueViewController` _a lot_ by removing the request and having to rebuild the timeline....

I think I'm going to build this today.

**Comment by BasThomas** [comment]
Seems 👍

**Comment by Sherlouk** [comment]
I'm glad it took you an entire minute to decide that was the right idea 😂 Sounds good!

**Comment by Sherlouk** [comment]
It's worth remembering that GQL allows you to query the total count, even if you don't load them at no extra cost to rate limits. So we can give accurate information without hurting them, and they just tap what they actually wanna see ("buy")

**Comment by rnystrom** [comment]
Ya the only thing misleading with showing the count is that it’s only a count of **root** comments. If there’s a PR with one thread of 100 comments, the total count still just says “1”.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Gonna land so we can try this out in TF

**Pull request merged**
