### PR TITLE
Background and border for managing actions

### PR DESCRIPTION
**Pull request by rnystrom**
I'm not sure I'm sold on this. What do you think?

simulator screen shot - iphone 8 - 2017-11-21 at 15 59 03

### CODE REVIEW

**Comment by Sherlouk** [comment]
I'd say it definitely needs some more padding outside of the container for example above the title. But I quite like it! Especially if we get a row 2 with things like lock & close! I think it looks nice!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I think what’s definitely off atm is the spacing from the bottom to the title. Think it would help if that was the same spacing as the bottom of the title to the comment. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
+1 on the spacing
Maybe remove the borders?
I️ also feel like it is kind of weird to split the issue/PR status from the other details. May look better if the status were to slide down with the other details somehow?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Also now seeing that manage isn’t vertically centered with the merge status. 🙈

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I'm gonna let this simmer for a bit, really not crazy about it. Agree w/ the point about moving the status, but that makes things unnecessarily complicated.

**Comment by rnystrom** [comment]
Not feeling this

**Pull request closed without merging**
