### PR TITLE
Fixing files dont have code highlighting

### LINKED ISSUE #1454: Some IGListKit Objective-C files don't have code highlighting
Go to IGListKit/Source/IGListAdapter.h and .m, they aren't highlighted. Not sure why.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Hey guys :)
I think this fixes #1454

### CODE REVIEW

**Comment by rnystrom** [comment]
Looks great, let’s do it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucianoPAlmeida** [comment]
Hey @rnystrom there's some reason for the CI does not run in the PR's ?

**Comment by SD10** [comment]
@LucianoPAlmeida we have to turn on a setting in buddy build that allows PRs from forks to be built automatically. GitHawk CI is kinda all over the place right now as everyone is trying to find a new, reliable provider

**Comment by LucianoPAlmeida** [comment]
I see :) 
Thank's @SD10 👍

**Comment by rnystrom** [comment]
Aha, thanks @SD10. Now that we’re moving to Bitrise I’ll see if that’s a thing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Hmm I do have builds setup for PRs, and [this answer](https://discuss.bitrise.io/t/building-forked-projects/3415/2) makes it clear that this is supposed to work. Next time we have a fork PR I'll see what's up.

**Pull request merged**
