### PR TITLE
Hides "Mark All" button when there is no "Unread" message

### LINKED ISSUE #821: Inbox - mark all button visible all the time
When we have inbox zero, expecting the "Mark Al"l button to be disabled. But in current build its always visible. 

On click "Mark All", triggering request but it's not disabling itself.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by rizwankce**
Closes #821

### CODE REVIEW

**Comment by rizwankce** [comment]
A quick test seems to be working but not sure using `notificationIDs.count` to update the status is correct. Need some help in reviewing @rnystrom

**Comment by rnystrom** [comment]
This is better than where I [added it before](https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NotificationsViewController.swift#L197), that's way too side-effect-ish. Maybe we can remove that entirely?

**Comment by rizwankce** [comment]
Yup. we can totally remove that. Literally, I placed breakpoints all over and figured out this fix. 😆

**Comment by BasThomas** [comment]
Thanks for this @rizwankce! Super annoying bug 😛

**Pull request merged**
