### PR TITLE
Load cache before network for GraphQL queries

### LINKED ISSUE #104: Load issue/PR from cache before network
Apollo has a "cache or network" flag, but I want a "cache **then** network" setup. Might have to do this manually, dunno.

### PR DESCRIPTION
**Pull request by joerocca**
Closes #104

Changed cache policy from `.fetchIgnoringCacheData` to `.returnCacheDataAndFetch`
Added in https://github.com/apollographql/apollo-ios/pull/129

### CODE REVIEW

**Comment by rnystrom** [comment]
@joerocca how does this impact scrolling to the bottom of issues? Does it scroll to the bottom of the cache content and then not scroll when the network loads?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
Oh shoot, I think it only scrolls to the bottom of the cached content. Will look into this once I get to a computer!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
Keep getting rate limited while investigating this haha

**Comment by rnystrom** [comment]
Doing some cleanup, we can revisit once this becomes more in-demand.

**Pull request closed without merging**
