### PR TITLE
Fix landscape view overlap for Login

### LINKED ISSUE #480: Landscape view overlap for Login
This looks like a constraint issue in LoginSplashViewController.
Note: Only affects iPhone, iPad is fine. 

## Steps to Reproduce
1. Launch app in unauthenticated state or log out
2. Rotate the screen if you're in portrait orientation
3. Observe that the subtitle label overlaps the sign in button.

### iPhone 6S
simulator screen shot - iphone 6s - 2017-10-01 at 14 24 56

### iPhone 6S+

simulator screen shot - iphone 6s plus - 2017-10-01 at 14 27 18

Version 1.10.0 (1900)
Device: iPhone 6s (iOS 10.3.3) 
TestFlight: false

### PR DESCRIPTION
**Pull request by ajfigueroa**
Fixes #480 

- Using [size classes](https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/TheAdaptiveModel.html#//apple_ref/doc/uid/TP40007457-CH19-SW4), I've tweaked the layout for the `Compact Height` size class which only affects iPhones in landscape.
- iPad remains unchanged

### Changes:
- For the existing vertical spacing constraints:
  - I've approximately halved them for landscape
- Due to layout issues with the iPhone 5/5S/5SE:
  - For all size classes, I've fixed the width and height to the logo image size (174x174)
  - I've then opted to reduce the size to about 80% of the original size for the `Compact Height` size class
  - I've decided on this percentage as I felt it was the reduction that looked the best but I'm open to changes! See my percentage comparisons [here](https://gist.github.com/ajfigueroa/ece4cb636058a3c4d8b0aeb76d59d1b1)

#### iPhone 5
simulator screen shot - iphone 5s - 2017-10-02 at 01 11 02

#### iPhone 6
simulator screen shot - iphone 6s - 2017-10-02 at 01 11 56

#### iPhone 6+

simulator screen shot - iphone 6s plus - 2017-10-02 at 01 12 29

#### iPhone X
simulator screen shot - iphone x - 2017-10-02 at 01 13 11

### CODE REVIEW

**Comment by BasThomas** [comment]
Seems like the button isn't in the safe area on iPhone X, is that something you'd be up to fixing as well? :)

**Comment by ajfigueroa** [comment]
@BasThomas Yeah, definitely! I'll look into this tonight and update the PR accordingly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ajfigueroa** [comment]
Updated with safe area layout support as per this [article](https://useyourloaf.com/blog/safe-area-layout-guide/). Apparently, this is compatible with iOS 10 devices too. 

I'm assuming this project is building with Xcode 9 but please correct me if I'm wrong?
I can verify how this looks like in Xcode 8 if needed.

### Updated iPhone X Screenshot

simulator screen shot - iphone x - 2017-10-02 at 23 07 24

**Comment by BasThomas** [comment]
I'm pretty sure Ryan has been using Xcode 9 to upload, yeah.

**Pull request merged**
