### PR TITLE
Release notifications

### PR DESCRIPTION
**Pull request by rnystrom**
Only thing I can't quite figure out is how to link to it... We get an API path that we can extract the id from, like this:

https://api.github.com/repos/facebook/Docusaurus/releases/9721470

Where `9721470` is the ID. But I'm not sure how to link it to [the actual release](https://github.com/facebook/Docusaurus/releases/tag/v1.0.7).

Any ideas?

Shot of it working:

simulator screen shot - iphone x - 2018-02-19 at 22 32 26

### CODE REVIEW

**Comment by rizwankce** [comment]
if we can get the tag name, then we can do something like below

`https://github.com/facebook/Docusaurus/releases/tag/v1.0.7` to link to it

**Comment by Sherlouk** [comment]
Totally misread this as you wanted to do push notifications for releases 🤦‍♂️

**Comment by rnystrom** [comment]
@rizwankce nice! Tag name exists, we can use that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I’m just gonna cheat and do an extra network request to get the tag name.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
