### PR TITLE
Fix/actionsheet location for ipad

### LINKED ISSUE #1343: Actionsheet location off
Especially when the keyboard is up

GitHawk Upload by BasThomas

GitHawk Upload by BasThomas

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1514903367)
Device: iPad7,3 (iOS 11.2.1)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by rizwankce**
Fixes #1343 

screen shot 2018-01-06 at 3 39 39 pm

@BasThomas  I'm trying to set source rect for presentation controller. Not sure this is better than what we have now

### CODE REVIEW

**Comment by BasThomas** [comment]
Yeah that’s better - how does it look without the keyboard up?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@BasThomas THis how it is when the keyboard is not up.

screen shot 2018-01-06 at 5 10 59 pm

**Comment by BasThomas** [comment]
🤔 not sure if that’s a big improvement. :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@BasThomasI'm having the same thinking. but not sure how to fix this 🤷‍♂️

**Pull request closed without merging**
