### PR TITLE
Use new dropdown for browsing files

### LINKED ISSUE #1267: Dropdown from file navigation and select path
- Add a small carrot to the title
- Tap and show a dropdown of file paths (overlay content)
- Tapping a path pops back to that VC

Easy way to go back vs tapping back button over & over.

Would justify having a control for the inbox nav design too.

(Using Photos.app markup)

GitHawk Upload by rnystrom

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by rnystrom**
Fixes #1267

simulator screen shot - iphone x - 2018-01-13 at 16 26 16

### CODE REVIEW

**Comment by rnystrom** [comment]
I ❤️  this so much, so easy to use

**Comment by BasThomas** [comment]
Looks cool! Not too sure how, but I feel like we can add a bit more context to explain the actions. What about a "Jump to..." title for the sheet?

**Comment by rnystrom** [comment]
Love it!

**Comment by BasThomas** [comment]
[Done](https://github.com/rnystrom/GitHawk/pull/1405)

**Pull request merged**
