### PR TITLE
Add title/subtitle header style and use for Issues

### PR DESCRIPTION
**Pull request by rnystrom**
Making room. I'm going to move bookmark actions to a nav bar item. Prepping some action cleanup and UI polish.

What do you like, thin + dark or bold + light on the subtitle? I lean bold+light (bold+dark isn't enough contrast).

img_6500

img_6501

### CODE REVIEW

**Comment by heshamsalman** [comment]
thin/dark

**Comment by BasThomas** [comment]
Team bold/light 👋

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Joining Bold/Light

**Comment by rnystrom** [comment]
Bold light wins!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
I was late to the party. Guess my team already won 😍. Bold / light. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
