### PR TITLE
Replace image upload images with text, hook up cancel button

### LINKED ISSUE #662: Image upload bar items should match rest of app
- Words, not symbols
- Blue

### LINKED ISSUE #665: Image upload cancel button doesn't work
Hitting the "X" does nothing. Should give an "Are you sure?" style alert before discarding.

### LINKED ISSUE #673: Missing NSPhotoLibraryUsageDescription permissions from image upload
Blocked on TestFlight atm, cc @Sherlouk

### PR DESCRIPTION
**Pull request by Sherlouk**
Fixes #662 
Fixes #665 
Fixes #673 

#664 would require a fair bit more work to remove the borders as it uses a UITableView in the grouped style. Would have to redo quite a bit to not use a UITableView for that bit

### CODE REVIEW

**Comment by rnystrom** [comment]
> #664 would require a fair bit more work to remove the borders as it uses a UITableView in the grouped style.

Pretty sure you can hack it and manually change the `separatorInset` to some huge `left` value that is off screen.

**Comment by rnystrom** [comment]
Thanks for the quick turn around! Merging now to unblock and get moving.

**Comment by Sherlouk** [comment]
Tried slamming the separatorInset to 10000 and it didn't seem to do a thing - Maybe white w/ border?

image

**Comment by rnystrom** [comment]
Ya les do white

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
