### PR TITLE
User can receive search results while typing

### LINKED ISSUE #596: Search while typing broken (Search tab)
Only searches when tapping search

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2092)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by heshamsalman**
Enables search while typing. 
Pointing at my other branch until it gets merged to master since it relies on some of those changes. 

Closes #596

### CODE REVIEW

**Comment by viktorgardart** [comment]
I like the feature, I personally don't like that what you're searching for is showing up in "recent" before the actual response is shown. 😅

**Comment by heshamsalman** [comment]
Good call @orta

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@heshamsalman lmk when this is good to merge (just merged the other PR)

**Comment by heshamsalman** [comment]
@rnystrom should be rebased on master now :+1:

**Pull request merged**
