### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by rnystrom**
Tests were failing to build after merging #809

### CODE REVIEW

**Comment by Sherlouk** [comment]
@rnystrom We should probably move to using `@testable` to prevent these issues again! 😅

**Comment by rnystrom** [comment]
@Sherlouk what’s that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
It imports the main project as a module like you could with any Pod, but the `@testable` attribute allows you to have access to all internal functions

Means you don't need to target files to the tests class!

**Comment by BasThomas** [comment]
Also what about running the unit tests on CI? 😄

**Comment by rnystrom** [comment]
@Sherlouk oh snap that's awesome!

@BasThomas they already do! [example](https://dashboard.buddybuild.com/apps/59d904ff8588d60001729c4e/build/5a12496995807f00017ce81d#tests)

**Comment by BasThomas** [comment]
🤔 why wasn't this caught then?

**Comment by rnystrom** [comment]
I merged the double tap Pr without looking 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
