### PR TITLE
Fixes bookmark Clear All and swipe to delete

### LINKED ISSUE #710: Bookmarks Clear All enabled after manually deleting entries
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1079)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

### PR DESCRIPTION
**Pull request by rizwankce**
Closed #710 #705

### CODE REVIEW

**Comment by heshamsalman** [comment]
@rizwankce do you mind closing in favor of #720?

**Comment by heshamsalman** [comment]
@rizwankce heads up there'll be conflicts with my branch #720, i've pulled in your changes to match behavior with the new swipe

**Comment by rizwankce** [comment]
@heshamsalman so we can close this PR. Isn't?

**Comment by heshamsalman** [comment]
@rizwankce yup, should be able to. sorry to eat your PR  🍔

**Comment by rizwankce** [comment]
Closing this in favour of #720

**Pull request closed without merging**
